# Generated by Django 3.1.7 on 2021-03-28 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.IntegerField()),
                ('specialty', models.CharField(max_length=30)),
                ('degree', models.CharField(max_length=30)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('reserved', 'رزرو شده'), ('free', 'خالی'), ('canceled', 'لغو شده')], max_length=10)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Project1.doctor')),
            ],
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
