# Generated by Django 3.1.7 on 2021-03-28 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0002_auto_20210328_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visittime',
            old_name='time',
            new_name='doctor',
        ),
    ]
