# Generated by Django 3.1.7 on 2021-03-28 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='user',
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
