# Generated by Django 3.1.7 on 2021-03-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0006_comments_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='text',
            new_name='commenttext',
        ),
    ]
