# Generated by Django 3.1.7 on 2021-03-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project1', '0010_auto_20210330_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visittime',
            name='status',
            field=models.CharField(choices=[('reserved', 'رزرو شده'), ('free', 'خالی'), ('canceled', 'لغو شده')], max_length=10),
        ),
        migrations.DeleteModel(
            name='VisitStatus',
        ),
    ]
